### ISSUE TITLE
Error running composer install

### ISSUE THREAD

**Issue by iraldoad** [lorisleiva/laravel-docker#102]
I am getting this error in my pipelines when running composer install. Last week it worked without errors. I found that if I remove the artifacts and the cache, it works. Please, help.

![imagen](https://user-images.githubusercontent.com/15159678/145058629-68bd6d71-a72d-4348-a45c-e3d00f4a2b4a.png)

GitlabCI

```yml
stages:
  - build
  - test
  - deploy

image: lorisleiva/laravel-docker:8.0

services:
  - postgres:13.4-alpine
  - redis:6.2.5-alpine

build:
  stage: build
  script:
    - cp .env.testing.example .env
    - cp .env.testing.example .env.testing
    - composer install
    - php artisan l5-swagger:generate
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/

phpunit:
  stage: test
  dependencies:
    - build
  script:
    - php artisan migrate --seed
    - phpunit --coverage-text --colors=never

codestyle:
  stage: test
  dependencies: []
  script:
    - phpcs
```
