### ISSUE TITLE
Segmentation fault with 7.1

### ISSUE THREAD

**Issue by Tisseur2Toile** [lorisleiva/laravel-docker#25]
Hello,

I'm very new to Gitlab CI and I found your article great. Although I tried to setup a simple gitlab CI using the 7.1 (as I want my project to be compatible with this version of PHP), I setup the Gitlab CI yml like this :
```
image: lorisleiva/laravel-docker:7.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

phpunit:
  stage: test
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
    - phpunit --coverage-text --colors=never
```

In this case (using 7.1 instead of latest) the test suite failed returning a ```Segmentation fault```
If I switch 7.1 for latest everything is working fine, did I do something wrong ?
