### ISSUE TITLE
Gitlab pipeline failed - iconv(): Wrong encoding

### ISSUE THREAD

**Issue by nsaumini** [lorisleiva/laravel-docker#70]
.gitlab-ci.yml
```

image: lorisleiva/laravel-docker:8.0

stages:
  - setup
  - test

prepare:
  stage: setup
  cache:
    key: "reports-application-$CI_COMMIT_BRANCH"
    paths:
      - .env
      - vendor
    policy: push
  script:
    - cp .env.example .env
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - php artisan key:generate

unit_test:
  stage: test
  cache:
    key: "reports-application-$CI_COMMIT_BRANCH"
    paths:
      - .env
      - vendor
    policy: pull
  script:
    - vendor/bin/phpunit

```
On test stage, I'm getting following error `ErrorException: iconv(): Wrong encoding, conversion from "ASCII" to "Windows-1252//TRANSLIT" is not allowed`

Can anyone help me to resolve this issue ?
